# Generated by Django 3.2.9 on 2021-11-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='birth_place',
        ),
        migrations.AddField(
            model_name='writer',
            name='birth_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birthdata.town', verbose_name='место рождения'),
        ),
    ]
