# Generated by Django 3.2.9 on 2021-11-11 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('birthdata', '0002_auto_20211111_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата рождения'),
            preserve_default=False,
        ),
    ]
