# Generated by Django 3.1.2 on 2021-11-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdata', '0003_writer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название города'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='birth_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writers', to='birthdata.town', verbose_name='место рождения'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='writer',
            constraint=models.UniqueConstraint(fields=('firstname', 'lastname', 'patronymic'), name='unique_writer'),
        ),
    ]
