# Generated by Django 3.1.2 on 2021-11-13 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdata', '0004_auto_20211113_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='birth_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writers', to='birthdata.town', to_field='name', verbose_name='место рождения'),
        ),
    ]
